In [1]:
%pip install pinecone

  Using cached packaging-24.2-py3-none-any.whl (65 kB)
  Attempting uninstall: packaging
    Found existing installation: packaging 25.0
    Uninstalling packaging-25.0:
      Successfully uninstalled packaging-25.0
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\kumar\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [3]:
from pinecone import Pinecone

pc = Pinecone(api_key="pcsk_694HBP_BonQ7uBqtboXnNpMFtDASfmhAW4ixsJd9V6488Ba86qKEamLa7Riq4NCFT9CcYK")
index = pc.Index("kumarindex")

In [5]:
type(index) #index

pinecone.db_data.index.Index

In [6]:
texts = [
    "Deepak Kumar Mohanty was born in Balasore, Odisha, India, to a humble and supportive family.",
    "From an early age, he was deeply curious about how machines work and how technology shapes the world.",
    "Despite challenges, Deepak’s determination to learn and grow never faded.",
    "He earned his Bachelor’s degree in Computer Applications (BCA) from Bhadrak Autonomous College, Odisha.",
    "Deepak is a passionate Python developer and aspiring Data Scientist with strong analytical and problem-solving skills.",
    "He has hands-on experience with Python, Django, Flask, HTML, CSS, JavaScript, and various Data Science tools.",
    "Driven by curiosity, he constantly explores AI, machine learning, and data visualization to expand his expertise.",
    "Deepak created multiple real-world projects — from a Netflix clone to data analysis dashboards — showcasing both creativity and logic.",
    "He actively shares valuable Python insights and learning tips on LinkedIn to help others grow in their tech journey.",
    "Deepak’s story reflects passion, perseverance, and the belief that continuous learning can transform one’s life."
]

In [ ]:

import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-47df70dff217e205cf4b860bbb11ff1556a1ab993f374b1de33cd037823e0abf"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding

In [8]:
embeddings = [generate_embeddings(text) for text in texts]

In [9]:
embeddings

[array([ 0.05874618,  0.01716367, -0.03385057, ...,  0.00438938,
        -0.00146788, -0.02586988], shape=(1536,)),
 array([ 0.00860733,  0.00794669, -0.03793576, ..., -0.0218264 ,
         0.00357315, -0.02698444], shape=(1536,)),
 array([ 0.00157107, -0.00291296,  0.01863574, ..., -0.00658583,
         0.01002349, -0.01296661], shape=(1536,)),
 array([ 0.01711475, -0.01486012,  0.04820827, ..., -0.01766816,
         0.02066069,  0.0024327 ], shape=(1536,)),
 array([ 0.03920899, -0.01062005,  0.01380038, ..., -0.02896377,
         0.02812325, -0.01156847], shape=(1536,)),
 array([-0.03450021,  0.01461001,  0.0322181 , ..., -0.02877255,
        -0.0201475 , -0.02002444], shape=(1536,)),
 array([-0.01524461, -0.01135506,  0.02394031, ..., -0.03263601,
        -0.03668837, -0.01676425], shape=(1536,)),
 array([ 0.02259899,  0.0227703 ,  0.02242768, ..., -0.02432639,
         0.02302727, -0.02324141], shape=(1536,)),
 array([-0.01527787, -0.06384856,  0.00627351, ..., -0.02923696,
       

In [11]:
index.upsert(
    vectors=[(
        str(0),
        embeddings[0].tolist(),
        {"text": texts[0]}
    )]
)

{'upserted_count': 1}

In [12]:
texts[0]

'Deepak Kumar Mohanty was born in Balasore, Odisha, India, to a humble and supportive family.'

In [13]:
embeddings[0]

array([ 0.05874618,  0.01716367, -0.03385057, ...,  0.00438938,
       -0.00146788, -0.02586988], shape=(1536,))

In [16]:
records = []
for i in range(len(texts)):
    records.append((str(i), embeddings[i], {"text": texts[i]} ))

In [17]:
records[0]

('0',
 array([ 0.05874618,  0.01716367, -0.03385057, ...,  0.00438938,
        -0.00146788, -0.02586988], shape=(1536,)),
 {'text': 'Deepak Kumar Mohanty was born in Balasore, Odisha, India, to a humble and supportive family.'})

In [18]:
index.upsert(vectors=records)

{'upserted_count': 10}

In [19]:
query = "Deepak is a passionate Python developer and aspiring Data Scientist"

In [25]:
qure_embed = generate_embeddings(query).tolist()

In [26]:
index.query(vector=qure_embed, top_k=2, include_metadata=True)

{'matches': [{'id': '4',
              'metadata': {'text': 'Deepak is a passionate Python developer '
                                   'and aspiring Data Scientist with strong '
                                   'analytical and problem-solving skills.'},
              'score': 0.951511443,
              'values': []},
             {'id': '9',
              'metadata': {'text': 'Deepak’s story reflects passion, '
                                   'perseverance, and the belief that '
                                   'continuous learning can transform one’s '
                                   'life.'},
              'score': 0.577581346,
              'values': []}],
 'namespace': '',
 'usage': {'read_units': 1}}

In [27]:
pc.delete_index("kumarindex")