In [1]:
%pip install qdrant-client

  Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
  Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
  Using cached h11-0.16.0-py3-none-any.whl (37 kB)
  Using cached hpack-4.1.0-py3-none-any.whl (34 kB)
  Using cached hyperframe-6.1.0-py3-none-any.whl (13 kB)
  Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
  Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\kumar\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [2]:
from qdrant_client import QdrantClient

qdrant_client = QdrantClient(
    url="https://60bdb20b-28f8-4f06-bce0-c64df2d350a9.us-east4-0.gcp.cloud.qdrant.io:6333", 
    api_key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.cL27q5aPdz4E5NzHgQmTb5_x42Lm6lohnScgp5uXw_g",
)

print(qdrant_client.get_collections())

collections=[]


In [3]:
qdrant_client

In [4]:
collection_name = "kumar_story"

In [7]:
from qdrant_client import models
qdrant_client.recreate_collection(collection_name,vectors_config=models.VectorParams(size=1536, distance=models.Distance.COSINE))

C:\Users\kumar\AppData\Local\Temp\ipykernel_3332\1364035173.py:2: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  qdrant_client.recreate_collection(collection_name,vectors_config=models.VectorParams(size=1536, distance=models.Distance.COSINE))


True

In [8]:
data = """
Deepak Kumar Mohanty is from Balasore, Odisha, India. He completed his BCA at Bhadrak Autonomous College, Odisha, and is currently preparing for a Data Scientist role in the IT industry. Deepak is 21 years old, 172 cm tall, and weighs 91 kg. He is highly ambitious, committed to proving that it is possible to secure a Data Scientist job without a Master’s degree within 6 to 12 months. He describes himself as a fast learner, a good listener, and very flexible in adopting new technologies. He loves observing how machines work and is deeply fascinated by artificial intelligence and its impact on the IT industry.

Deepak has strong technical skills in Python, Django, Flask, and other Python tools, along with knowledge of HTML, CSS, and JavaScript. He has worked on multiple projects including a Netflix homepage clone using HTML and CSS, an e-commerce website clone, and a React calculator app that performs basic math operations with responsive design. He also built a GitHub repository called 'Kumar Projects' where he uploads data science-related work, such as the 'Analysis and Visualization of Global Population Data in 2021'. His dataset work includes analyzing data with columns such as Country Name and Population. Deepak’s GitHub projects are organized from basic to advanced, showcasing his growth in data science.

He is highly interested in statistics and hypothesis testing, and he has completed day 6 of a 'Statistics for Data Science' course. He often requests clear, step-by-step explanations in simple words and prefers visual aids or diagrams to fully understand complex topics. He explores advanced Python concepts such as interning, object identity for mutable and immutable types, duck typing, private member access, and the use of super() in class hierarchies. He also practices embeddings, vector search, and cosine similarity for NLP, where he once faced a 'ModuleNotFoundError: No module named sentence_transformers' issue and learned to install the missing library. Deepak relates the concept of vector norms to the Pythagoras theorem for better understanding.

Deepak is also active on LinkedIn, where he shares knowledge through carousels and posts about hidden Python concepts, tips, and memory optimization tricks. He once created a carousel explaining single-element tuples, another on Python interning, and one comparing object identity between immutable and mutable types. He prefers using dark, professional backgrounds for his carousel designs, with faded tones to highlight the content. His LinkedIn goals include growing his presence, creating a group focused on overlooked Python concepts, optimizing content with effective hashtags, and delivering value to the Python community.

In addition to data science, Deepak works on voice assistant projects. One of his key projects is JARVIS, a desktop voice assistant integrated with OpenAI. He experiments with libraries like pyttsx3, speech_recognition, and win32com for text-to-speech, and explores building user interfaces using Tkinter. He is curious about combining speech recognition with text-to-speech seamlessly on Windows. He enjoys hands-on experimentation and is enthusiastic about building real-world AI-powered applications.

Deepak follows Vishwa Mohan on YouTube for inspiration and learning. His personality blends technical curiosity with dedication and creativity. He enjoys exploring new concepts, sharing insights with others, and documenting his journey in tech. He values clarity and precision in communication and prefers avoiding pronouns in datasets to keep information unambiguous. Overall, Deepak is a motivated and passionate learner with strong technical skills, a growing project portfolio, and a clear vision to become a successful Data Scientist.
"""


In [9]:
clean_data = data.strip()

In [10]:
print(clean_data)

Deepak Kumar Mohanty is from Balasore, Odisha, India. He completed his BCA at Bhadrak Autonomous College, Odisha, and is currently preparing for a Data Scientist role in the IT industry. Deepak is 21 years old, 172 cm tall, and weighs 91 kg. He is highly ambitious, committed to proving that it is possible to secure a Data Scientist job without a Master’s degree within 6 to 12 months. He describes himself as a fast learner, a good listener, and very flexible in adopting new technologies. He loves observing how machines work and is deeply fascinated by artificial intelligence and its impact on the IT industry.

Deepak has strong technical skills in Python, Django, Flask, and other Python tools, along with knowledge of HTML, CSS, and JavaScript. He has worked on multiple projects including a Netflix homepage clone using HTML and CSS, an e-commerce website clone, and a React calculator app that performs basic math operations with responsive design. He also built a GitHub repository called 

In [11]:
len(clean_data)

3768

In [12]:
max_char = 500
overlap = 100
chunks = []
i = 0
while i< len(clean_data):
    piece = clean_data[i:i+max_char]
    chunks.append(piece)
    i = i+ max_char - overlap

In [13]:
chunks

['Deepak Kumar Mohanty is from Balasore, Odisha, India. He completed his BCA at Bhadrak Autonomous College, Odisha, and is currently preparing for a Data Scientist role in the IT industry. Deepak is 21 years old, 172 cm tall, and weighs 91 kg. He is highly ambitious, committed to proving that it is possible to secure a Data Scientist job without a Master’s degree within 6 to 12 months. He describes himself as a fast learner, a good listener, and very flexible in adopting new technologies. He loves',
 'himself as a fast learner, a good listener, and very flexible in adopting new technologies. He loves observing how machines work and is deeply fascinated by artificial intelligence and its impact on the IT industry.\n\nDeepak has strong technical skills in Python, Django, Flask, and other Python tools, along with knowledge of HTML, CSS, and JavaScript. He has worked on multiple projects including a Netflix homepage clone using HTML and CSS, an e-commerce website clone, and a React calcula

In [14]:
len(chunks)

10

In [15]:
import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-4aca7f0066db9e4df1204de08ff959f1dd8c0279d8750eff36de3a7bdb1e6101"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding

In [16]:
for i in chunks:
    embedding = generate_embeddings(i)
    print(embedding)

[ 0.02237804  0.01795307 -0.00452745 ...  0.01837507  0.03518271
 -0.02058153]
[-0.01348186 -0.0321741   0.00224046 ... -0.01961708  0.00827799
 -0.01762411]
[-0.03488477 -0.00471493 -0.02062185 ...  0.02100492  0.0101577
 -0.03258635]
[-0.00213516 -0.00912508  0.0679533  ... -0.00544583  0.03015129
 -0.03673941]
[-0.00049984  0.00327688  0.01935099 ... -0.00886498  0.01717274
 -0.02902649]
[ 0.00783338 -0.02858108 -0.00320946 ...  0.00291059  0.02553669
 -0.01619502]
[-0.00479376 -0.02589395  0.0594579  ... -0.00689534  0.00711393
 -0.02339352]
[-0.01993684 -0.02076978  0.01989654 ...  0.01121111  0.01378383
 -0.00910189]
[ 0.04160818 -0.02024986 -0.00312095 ...  0.01302452  0.023751
  0.00761059]
[ 0.03468012 -0.01795976  0.01304808 ...  0.01668594  0.02552237
 -0.00948482]


In [17]:
embed_list = []
meta = []

for idx , chunk in enumerate(chunks):
    vec = generate_embeddings(chunk)
    embed_list.append(vec.astype('float32'))
    meta.append({"id":idx , "text":chunk})

In [18]:
embed_list

[array([ 0.02240271,  0.01794146, -0.00456977, ...,  0.01835141,
         0.0352077 , -0.02056998], shape=(1536,), dtype=float32),
 array([-0.01348186, -0.0321741 ,  0.00224046, ..., -0.01961708,
         0.00827799, -0.01762411], shape=(1536,), dtype=float32),
 array([-0.03488477, -0.00471493, -0.02062185, ...,  0.02100492,
         0.0101577 , -0.03258635], shape=(1536,), dtype=float32),
 array([-0.00212678, -0.00915796,  0.06800397, ..., -0.00545227,
         0.03020333, -0.03673808], shape=(1536,), dtype=float32),
 array([-0.00049984,  0.00327688,  0.01935099, ..., -0.00886498,
         0.01717274, -0.02902649], shape=(1536,), dtype=float32),
 array([ 0.00783338, -0.02858108, -0.00320946, ...,  0.00291059,
         0.02553669, -0.01619502], shape=(1536,), dtype=float32),
 array([-0.00478341, -0.0259156 ,  0.05941101, ..., -0.00689318,
         0.00710032, -0.02335319], shape=(1536,), dtype=float32),
 array([-0.01991181, -0.02075826,  0.01991181, ...,  0.01121887,
         0.0137716

In [19]:
meta

[{'id': 0,
  'text': 'Deepak Kumar Mohanty is from Balasore, Odisha, India. He completed his BCA at Bhadrak Autonomous College, Odisha, and is currently preparing for a Data Scientist role in the IT industry. Deepak is 21 years old, 172 cm tall, and weighs 91 kg. He is highly ambitious, committed to proving that it is possible to secure a Data Scientist job without a Master’s degree within 6 to 12 months. He describes himself as a fast learner, a good listener, and very flexible in adopting new technologies. He loves'},
 {'id': 1,
  'text': 'himself as a fast learner, a good listener, and very flexible in adopting new technologies. He loves observing how machines work and is deeply fascinated by artificial intelligence and its impact on the IT industry.\n\nDeepak has strong technical skills in Python, Django, Flask, and other Python tools, along with knowledge of HTML, CSS, and JavaScript. He has worked on multiple projects including a Netflix homepage clone using HTML and CSS, an e-co

In [20]:
len(embed_list)

10

In [25]:
type(embed_list)

list

In [21]:
embeddings = np.array(embed_list)

In [22]:
embeddings

array([[ 0.02240271,  0.01794146, -0.00456977, ...,  0.01835141,
         0.0352077 , -0.02056998],
       [-0.01348186, -0.0321741 ,  0.00224046, ..., -0.01961708,
         0.00827799, -0.01762411],
       [-0.03488477, -0.00471493, -0.02062185, ...,  0.02100492,
         0.0101577 , -0.03258635],
       ...,
       [-0.01991181, -0.02075826,  0.01991181, ...,  0.01121887,
         0.01377166, -0.00911617],
       [ 0.0416159 , -0.02028066, -0.0031266 , ...,  0.0130337 ,
         0.02375541,  0.00763905],
       [ 0.0346763 , -0.0179922 ,  0.01305812, ...,  0.01666115,
         0.02551956, -0.00944935]], shape=(10, 1536), dtype=float32)

In [23]:
len(embeddings)

10

In [24]:
type(embeddings)

numpy.ndarray

In [33]:
points = []

for idx , (chunk,emb) in enumerate(zip(chunks,embeddings)):
    point = models.PointStruct(id=idx, vector=emb.astype('float32').tolist(), payload={"text":chunk})
    points.append(point)

In [34]:
points

[PointStruct(id=0, vector=[0.02240270934998989, 0.017941460013389587, -0.004569766577333212, 0.01358872652053833, -0.008114651776850224, 0.00416282843798399, -0.0006247257115319371, 0.03962072357535362, -0.013009969145059586, -0.024524817243218422, 0.05488543212413788, -0.032048653811216354, -0.010146329179406166, -0.014758297242224216, 0.07818038761615753, 0.024199265986680984, -0.012274465523660183, -0.021763665601611137, -0.004985748324543238, 0.04497422277927399, 0.02990243211388588, -0.022101273760199547, 0.03132520988583565, -0.029733628034591675, 0.052473943680524826, 0.01112298108637333, 0.009814749471843243, 0.004988762550055981, 0.019207488745450974, -0.014782411977648735, 0.02444041520357132, -0.009477141313254833, -0.014107195660471916, 0.008512547239661217, 0.05011068657040596, -0.03419487923383713, -0.041549909859895706, -0.023584337905049324, -0.008512547239661217, -0.029444249346852303, -0.015144134871661663, -0.09573601186275482, -0.029371904209256172, 0.05454782396554

In [35]:
qdrant_client.upsert(
    collection_name=collection_name,
    points=points
)

UpdateResult(operation_id=0, status=<UpdateStatus.COMPLETED: 'completed'>)

In [36]:
query = "What is Deepak Kumar Mohanty's educational background?"
query_vec = generate_embeddings(query).astype('float32').tolist()

In [37]:
query_vec

[-0.013712313957512379,
 -0.02778399921953678,
 -0.018799683079123497,
 0.02931133285164833,
 -0.026683421805500984,
 0.007928659208118916,
 0.014925196766853333,
 0.08350922167301178,
 -0.021618511527776718,
 -0.02791876532137394,
 0.03418532386422157,
 -0.020495472475886345,
 -0.001722462009638548,
 -0.025268390774726868,
 0.05875743180513382,
 0.025156086310744286,
 -0.012926185503602028,
 -0.008304878138005733,
 0.01303848996758461,
 0.06634917855262756,
 0.05323207750916481,
 -0.021259140223264694,
 0.023381683975458145,
 -0.016811903566122055,
 0.02141636610031128,
 -0.009074159897863865,
 -0.008040963672101498,
 -0.0190579816699028,
 0.02016979083418846,
 0.006423786748200655,
 0.021809428930282593,
 -0.01531826052814722,
 -0.01769910380244255,
 0.036386482417583466,
 0.02043932117521763,
 -0.00997820682823658,
 -0.051300447434186935,
 0.0025843949988484383,
 -0.028951961547136307,
 -0.031557414680719376,
 0.0091471578925848,
 -0.10394854843616486,
 -0.05062662437558174,
 0.0624

In [38]:
len(query_vec)

1536

In [39]:
qdrant_client.search(
    collection_name=collection_name,
    query_vector=query_vec,
    limit=3, with_payload=True
)

C:\Users\kumar\AppData\Local\Temp\ipykernel_3332\1505107880.py:1: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  qdrant_client.search(


[ScoredPoint(id=0, version=0, score=0.6972057, payload={'text': 'Deepak Kumar Mohanty is from Balasore, Odisha, India. He completed his BCA at Bhadrak Autonomous College, Odisha, and is currently preparing for a Data Scientist role in the IT industry. Deepak is 21 years old, 172 cm tall, and weighs 91 kg. He is highly ambitious, committed to proving that it is possible to secure a Data Scientist job without a Master’s degree within 6 to 12 months. He describes himself as a fast learner, a good listener, and very flexible in adopting new technologies. He loves'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=9, version=0, score=0.4872357, payload={'text': 'erall, Deepak is a motivated and passionate learner with strong technical skills, a growing project portfolio, and a clear vision to become a successful Data Scientist.'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=8, version=0, score=0.45820367, payload={'text': 'ld AI-powered applications.\n\nD

In [63]:
def user_query(query):
    query_vec = generate_embeddings(query).astype('float32').tolist()
    search_v = qdrant_client.search(collection_name=collection_name, query_vector=query_vec, limit=3, with_payload=True)
    return search_v

In [64]:
user_query("what is the qualification of deepak")

C:\Users\kumar\AppData\Local\Temp\ipykernel_3332\36031674.py:3: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  search_v = qdrant_client.search(collection_name=collection_name, query_vector=query_vec, limit=3, with_payload=True)


[ScoredPoint(id=9, version=0, score=0.64394116, payload={'text': 'erall, Deepak is a motivated and passionate learner with strong technical skills, a growing project portfolio, and a clear vision to become a successful Data Scientist.'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=0, version=0, score=0.5382571, payload={'text': 'Deepak Kumar Mohanty is from Balasore, Odisha, India. He completed his BCA at Bhadrak Autonomous College, Odisha, and is currently preparing for a Data Scientist role in the IT industry. Deepak is 21 years old, 172 cm tall, and weighs 91 kg. He is highly ambitious, committed to proving that it is possible to secure a Data Scientist job without a Master’s degree within 6 to 12 months. He describes himself as a fast learner, a good listener, and very flexible in adopting new technologies. He loves'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=8, version=0, score=0.53535473, payload={'text': 'ld AI-powered applications.\n\n