In [1]:
%pip install weaviate-client

  Using cached deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\kumar\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [2]:
pip show weaviate-client

Name: weaviate-client
Version: 4.17.0
Summary: A python native Weaviate client
Home-page: https://github.com/weaviate/weaviate-python-client
Author: Weaviate
Author-email: hello@weaviate.io,
License: BSD 3-clause
Location: c:\users\kumar\appdata\local\programs\python\python310\lib\site-packages
Requires: validators, grpcio, protobuf, deprecation, pydantic, authlib, httpx
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [ ]:
import weaviate
from weaviate.classes.init import Auth

# Best practice: store your credentials in environment variables
weaviate_url = "feuthugqsgyrhb3s0nzl8q.c0.asia-southeast1.gcp.weaviate.cloud"
weaviate_api_key = "VnJIL3NqWnV0T1ZsU3ZIc192RnJQSC9ncklMVlIwQkNGSUJLS3BZUXJUWjFLU3BUYWNvbldKdXhCYXJzPV92MjAw"

# Connect to Weaviate Cloud
client = weaviate.connect_to_weaviate_cloud(
    cluster_url=weaviate_url,
    auth_credentials=Auth.api_key(weaviate_api_key),
)

print(client.is_ready())

True


In [9]:
texts = [
    "Deepak Kumar Mohanty was born in Balasore, Odisha, India, to a humble and supportive family.",
    "From an early age, he was deeply curious about how machines work and how technology shapes the world.",
    "Despite challenges, Deepak’s determination to learn and grow never faded.",
    "He earned his Bachelor’s degree in Computer Applications (BCA) from Bhadrak Autonomous College, Odisha.",
    "Deepak is a passionate Python developer and aspiring Data Scientist with strong analytical and problem-solving skills.",
    "He has hands-on experience with Python, Django, Flask, HTML, CSS, JavaScript, and various Data Science tools.",
    "Driven by curiosity, he constantly explores AI, machine learning, and data visualization to expand his expertise.",
    "Deepak created multiple real-world projects — from a Netflix clone to data analysis dashboards — showcasing both creativity and logic.",
    "He actively shares valuable Python insights and learning tips on LinkedIn to help others grow in their tech journey.",
    "Deepak’s story reflects passion, perseverance, and the belief that continuous learning can transform one’s life."
]

In [10]:
import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-47df70dff217e205cf4b860bbb11ff1556a1ab993f374b1de33cd037823e0abf"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding

In [11]:
embeddings = [generate_embeddings(text) for text in texts]

In [12]:
embeddings

[array([ 0.05878288,  0.01717264, -0.0338271 , ...,  0.00438903,
        -0.0014833 , -0.02586778], shape=(1536,)),
 array([ 0.00860733,  0.00794669, -0.03793576, ..., -0.0218264 ,
         0.00357315, -0.02698444], shape=(1536,)),
 array([ 0.00157107, -0.00291296,  0.01863574, ..., -0.00658583,
         0.01002349, -0.01296661], shape=(1536,)),
 array([ 0.01709679, -0.01486232,  0.0482154 , ..., -0.01766053,
         0.02067399,  0.00244075], shape=(1536,)),
 array([ 0.03916692, -0.0105021 ,  0.01395733, ..., -0.02891487,
         0.02814199, -0.01163869], shape=(1536,)),
 array([-0.03450021,  0.01461001,  0.0322181 , ..., -0.02877255,
        -0.0201475 , -0.02002444], shape=(1536,)),
 array([-0.01525764, -0.01136182,  0.02394184, ..., -0.03263809,
        -0.03666659, -0.01676531], shape=(1536,)),
 array([ 0.02259899,  0.0227703 ,  0.02242768, ..., -0.02432639,
         0.02302727, -0.02324141], shape=(1536,)),
 array([-0.01527787, -0.06384856,  0.00627351, ..., -0.02923696,
       

In [14]:
collection = client.collections.get("Documents")

collection.data.insert(
    properties={"text": texts[0]},
    vector=embeddings[0].tolist()
)


UUID('c11c2379-3af7-4233-973c-5b4e87425d8b')

In [ ]:
collection = client.collections.get("Documents")

for i in range(len(texts)):
    collection.data.insert(
        properties={"text": texts[i]},
        vector=embeddings[i].tolist()
    )


In [17]:
query = "from a Netflix clone to data analysis dashboards"

In [18]:
embeddings_query = generate_embeddings(query)

In [ ]:
query_embedding = embeddings[0].tolist()  # or embedding from OpenAI, Gemini, etc.

result = collection.query.near_vector(
    near_vector=embeddings_query,
    limit=3  # number of top results to return
)

In [23]:
result.objects[0].properties["text"]

'Deepak created multiple real-world projects — from a Netflix clone to data analysis dashboards — showcasing both creativity and logic.'

In [21]:
for obj in result.objects:
    print("Text:", obj.properties["text"])
    print("Score:", obj.metadata.distance)  # lower distance = more similar
    print("-----")


Text: Deepak created multiple real-world projects — from a Netflix clone to data analysis dashboards — showcasing both creativity and logic.
Score: None
-----
Text: Driven by curiosity, he constantly explores AI, machine learning, and data visualization to expand his expertise.
Score: None
-----
Text: He has hands-on experience with Python, Django, Flask, HTML, CSS, JavaScript, and various Data Science tools.
Score: None
-----


In [27]:
client.collections.delete("Documents")
